application/core/views.py
from flask import render_template, Blueprint, redirect, url_for, flash, request, jsonify, make_response
from application.forms import login_form
from application.models import Users, Projects
from application import db
from flask_login import login_user, login_required, logout_user, current_user

core = Blueprint('core', __name__, template_folder = 'templates/core')

@core.route('/')
def index():
  return render_template('index.html')

@core.route('/login', methods=['post', 'get'])
def login():
  form = login_form()
  if form.validate_on_submit():
    this_user = Users.query.filter_by(email = form.email.data.lower()).first()
    if this_user is not None and this_user.check_password(form.password.data):
      login_user(this_user)
      flash(f'Welcome back, {this_user.display_name}')      
      return redirect(url_for('core.dashboard'))
    else:
      flash('You have provided a wrong email or password.')
      return redirect(url_for('core.login'))
  else:
    for field, error in form.errors.items():
      flash('{} ({} error)'.format(error[0], field))
  return render_template('login.html', form = form)

@core.route('/logout')
@login_required
def logout():
  logout_user()
  flash('Logged out.')
  return redirect(url_for('core.login'))

@core.route('/dashboard')
@login_required
def dashboard():
  my_projects = Projects.query.filter_by(user_id=current_user.id).all()
  if len(my_projects) == 0:
    my_projects = None
  return render_template('dashboard.html', my_projects=my_projects)

@core.route('/apps')
def apps():
  return render_template('apps.html')

application/templates/unilay.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Stimgen{% block page_title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://assets.theonline.app/unilay/css/unilay6.css"
    />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/fav.ico') }}"
    />
    {% block head_addons %}{% endblock %}
  </head>
  <body>
    <nav>
      <a href="{{ url_for('core.index') }}" id="logo-with-text">Stimgen</a>
      <div id="nav-menu">
        <ul id="nav-links">
          {% block custom_nav %}
          <li><a href="{{ url_for('core.apps') }}">Apps</a></li>
          <!-- <li><a href="">About</a></li> -->
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('core.dashboard') }}">Dashboard</a></li>
          <li><a href="{{ url_for('core.logout') }}">Logout</a></li>
          {% else %}
          <li><a href="{{ url_for('core.login') }}">Login</a></li>
          {% endif %} {% endblock %}
          <li id="close-button">Close</li>
        </ul>
        <button id="mobile-nav-button" class="hidden"></button>
      </div>
    </nav>
    <div id="shades" class="hidden"></div>
    {% for message in get_flashed_messages() %}
    <section class="confined rounded" id="notif{{loop.index}}">
      <div class="notification" onClick="dismissNotif('notif{{loop.index}}')">
        {{ message }}
      </div>
    </section>
    {% endfor %} {% block page_content %}
    <main class="confined">
      <section id="welcome" class="spacer-medium"></section>
    </main>
    {% endblock %}
    <footer>
      <div>&copy; SFU Vision Lab, 2021</div>
      <div>V3.0.0</div>
    </footer>
    <script src="https://unilay.theonline.app/js/uiToggles.js"></script>
  </body>
</html>