application/coblo/views.py
from flask import render_template, Blueprint, redirect, url_for, flash, request
import json
from application.forms import login_form, coblo_form, save_image_pair_form
from application.models import Users, Projects
from application import db
from flask_login import login_user, login_required, logout_user, current_user
import shortuuid

coblo = Blueprint('coblo', __name__, template_folder = 'templates/coblo')

@coblo.route('/')
@login_required
def index():
  return render_template('coblo-index.html')

@coblo.route('/run/<string:ref_id>/<string:run_mode>/<string:target_mode>/<string:gap>')
@login_required
def run(ref_id, run_mode, target_mode, gap):
  target_project = Projects.query.filter_by(ref_id=ref_id).first()
  form = save_image_pair_form()
  if target_project is None:
    flash('The requested project does not exist')
  return render_template('coblo-run.html', project_settings=target_project.config_JSON, form=form, run_mode=run_mode, ref_id=ref_id, target_mode=target_mode, gap=gap)

@coblo.route('/projects/<string:ref_id>', defaults={'ref_id': 'new'})
@coblo.route('/projects/<string:ref_id>', methods=['get', 'post'])
@login_required
def projects(ref_id):
  target_project = Projects.query.filter_by(ref_id=ref_id).first()
  if target_project is None:
    form = coblo_form()
    project_settings = None
    mode = 'create'
      
  else:
    form = coblo_form(obj=target_project)
    project_settings = target_project.config_JSON
    mode = 'edit'

  if form.validate_on_submit():
    new_JSON = json.dumps({
      "imageBackground":form.image_background.data,
      "imageWidth":form.image_width.data,
      "imageHeight":form.image_height.data,
      "outerMargins":form.outer_margins.data,
      "centralMargins":form.central_margins.data,
      "objectWidth":form.object_width.data,
      "objectHeight":form.object_height.data,
      "radial":{
        "radius": form.radius.data
      },
      "fixationCross": {
        "color":form.fixation_cross_color.data,
        "thickness":form.fixation_cross_thickness.data,
        "length":form.fixation_cross_length.data,
        "show":form.fixation_cross_show.data,
      },
      "debug":form.debug.data,
      "colors":form.colors.data.split(',')
    })
    if mode == 'edit':
      target_project.config_JSON = new_JSON
      db.session.commit()
      flash(f'Your settings for {target_project.name} have been updated.')
      return redirect(url_for('coblo.projects', ref_id=target_project.ref_id))
    elif mode == 'create':
      new_project = Projects(shortuuid.uuid(), current_user.id, form.name.data, form.description.data, new_JSON)
      db.session.add(new_project)
      db.session.commit()
      flash('Your new project has been created.')
      return redirect(url_for('coblo.projects', ref_id=new_project.ref_id))
  else:
    for field, error in form.errors.items():
      flash('{} ({} error)'.format(error[0], field))
  
  return render_template('coblo-projects.html', form=form, project_settings=project_settings, ref_id=ref_id)

application/coblo/templates/coblo/coblo-projects.html
{% extends 'unilay.html' %} {% block page_title %}Homepage{% endblock %} {%
block page_content %}
<main class="confined">
  <h1>Create a project</h1>
  <section>
    <form action="" method="POST">
      <div class="side-by-side spacer-medium">
        <div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Project Information</h2>
            {{ form.name.label }} {{ form.name }} {{ form.description.label }}
            {{ form.description }}
          </div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Image Setup</h2>
            {{ form.hidden_tag() }} {{ form.image_background.label }} {{
            form.image_background }} {{ form.image_width.label }} {{
            form.image_width }} {{ form.image_height.label }} {{
            form.image_height }}
          </div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Margins</h2>
            {{ form.outer_margins.label }} {{ form.outer_margins }} {{
            form.central_margins.label }} {{ form.central_margins }}
          </div>
        </div>
        <div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Objects Setup</h2>
            {{ form.object_width.label }} {{ form.object_width }} {{
            form.object_height.label }} {{ form.object_height }} {{
            form.radius.label }} {{ form.radius }} {{ form.colors.label }} {{
            form.colors }}
          </div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Fixation Cross Setup</h2>
            {{ form.fixation_cross_color.label }} {{ form.fixation_cross_color
            }} {{ form.fixation_cross_thickness.label }} {{
            form.fixation_cross_thickness }} {{ form.fixation_cross_length.label
            }} {{ form.fixation_cross_length }} {{ form.fixation_cross_show }}
            {{ form.fixation_cross_show.label }}
          </div>
          <div class="bg-white padded shadowed spacer-small">
            <h2>Debug Mode</h2>
            {{ form.debug }} {{ form.debug.label }}
          </div>
        </div>
      </div>
      <div class="padded bg-white shadowed spacer-small">
        {% if project_settings %}
        <p>
          Click on the button below to save your configuration, or
          <a
            href="{{ url_for('coblo.run', ref_id=ref_id, run_mode='change', target_mode='target', gap=0) }}"
            >run the project</a
          >.
        </p>
        {{ form.edit(class_='button-primary') }} {% else %}
        <p>
          If everything looks good click on the button below to create your
          project.
        </p>
        {{ form.create(class_='button-primary') }} {% endif %}
      </div>
    </form>
  </section>
</main>
<script>
  const renderConfig = () => {
    CONFIG = JSON.parse(`{{ project_settings|safe }}`);

    const imageBackground = document.getElementById("image_background");
    const imageWidth = document.getElementById("image_width");
    const imageHeight = document.getElementById("image_height");
    const outerMargins = document.getElementById("outer_margins");
    const centralMargins = document.getElementById("central_margins");
    const objectWidth = document.getElementById("object_width");
    const objectHeight = document.getElementById("object_height");
    const radius = document.getElementById("radius");
    const fixationCrossColor = document.getElementById("fixation_cross_color");
    const fixationCrossThickness = document.getElementById(
      "fixation_cross_thickness"
    );
    const fixationCrossLength = document.getElementById(
      "fixation_cross_length"
    );
    const fixationCrossShow = document.getElementById("fixation_cross_show");
    const debug = document.getElementById("debug");
    const colors = document.getElementById("colors");

    imageBackground.value = CONFIG.imageBackground;
    imageWidth.value = CONFIG.imageWidth;
    imageHeight.value = CONFIG.imageHeight;
    outerMargins.value = CONFIG.outerMargins;
    centralMargins.value = CONFIG.centralMargins;
    objectWidth.value = CONFIG.objectWidth;
    objectHeight.value = CONFIG.objectHeight;
    colors.value = CONFIG.colors;

    radius.value = CONFIG.radial.radius;
    fixationCrossColor.value = CONFIG.fixationCross.color;
    fixationCrossThickness.value = CONFIG.fixationCross.thickness;
    fixationCrossLength.value = CONFIG.fixationCross.length;

    debug.checked = CONFIG.debug;
    fixationCrossShow.checked = CONFIG.fixationCross.show;
  };

  // {% if project_settings %}
  renderConfig();
  // {% endif %}
</script>
{% endblock %}

application/coblo/templates/coblo/coblo-run.html
{% extends 'unilay.html' %} {% block head_addons %}
<style>
  canvas {
    max-width: 100%;
  }
</style>
{% endblock %} {% block page_title %}Colored Blocks Generator{% endblock %} {%
block page_content %}
<main class="confined">
  <h1>Colored Blocks Generator</h1>
  <section class="bg-white shadowed padded">
    <div>
      <h3>Current Changes</h3>
      Target displacement value:
      <span id="displayDisplacementValue">Undefined</span><br />
      Target displacement direction:
      <span id="displayDisplacementDirection">Undefined</span><br />
      Target manipulation type:
      <span id="displayTargetManipulationType">Undefined</span><br />
      Values will be undefined if images have not been generated yet.
    </div>
    <div class="side-by-side">
      <div>
        <canvas id="original"></canvas>
      </div>
      <div>
        <canvas id="modified"></canvas>
      </div>
    </div>
    <div class="side-by-side-flex">
      <div>
        <button onClick="regenerate()" class="custom button-secondary">
          Generate
        </button>
      </div>
      <div>
        <button onclick="toggleHighlight()" class="custom button-primary">
          Highlight
        </button>
      </div>
      <div>
        <button onClick="toggleElement('coord-form')" class="custom">
          Save/Edit
        </button>
      </div>
      <div>
        <a href="{{ url_for('coblo.projects', ref_id=ref_id) }}">
          <button class="custom">Settings</button>
        </a>
      </div>
    </div>
    <h3>Manipulation Target</h3>
    <div class="side-by-side-flex">
      <div>
        Mode
        <select id="runMode">
          <option value="change">Change</option>
          <option value="flip">Flip</option>
        </select>
      </div>
      <div>
        Target selection
        <select id="targetMode">
          <option value="target">Target</option>
          <option value="inverse">Inverse</option>
          <option value="all">All</option>
        </select>
      </div>
      <div>Gap<input id="gap" type="text" value="0" /></div>
    </div>
    <div>
      <input id="showLines" type="checkbox" />
      <label for="showLines"> Show connecting lines (if gap is present) </label>
      <br />
      <input id="whiteGap" type="checkbox" />
      <label for="whiteGap">White gaps</label>
      <br />
      <input id="showNumbers" type="checkbox" />
      <label for="showNumbers">Draw block numbers</label>
      <br />
      <input id="drawDiagonalLine" type="checkbox" />
      <label for="drawDiagonalLine">Draw diagonal line</label>
      <br />
      <input id="changePositionCheck" type="checkbox" />
      <label for="changePositionCheck"
        >Change target block position (does not work with 'inverse' or
        'all')</label
      >
      <select id="changePositionTypeSelect">
        <option value="overlap">Overlap</option>
        <option value="touch">Touch</option>
        <option value="separate">Separate</option>
      </select>
      <input
        type="text"
        id="changePositionMax"
        placeholder="max position change value"
      />
      <input
        type="text"
        id="changePositionMin"
        placeholder="min position change value"
      />
      <select id="changeDirectionValueSelect">
        <option value="topLeft">Top Left</option>
        <option value="topRight">Top Right</option>
        <option value="bottomLeft">Bottom Left</option>
        <option value="bottomRight">Bottom Right</option>
      </select>
    </div>

    <div id="coord-form" class="hidden">
      <form action="" method="GET">
        {{ form.hidden_tag() }} {{ form.stimulus_JSON }}
        <div class="side-by-side">
          <div>{{ form.save(class_="button-primary") }}</div>
          <div>
            <button type="button" class="custom" onClick="regenerate(true)">
              Edit Current Image
            </button>
          </div>
        </div>
      </form>
    </div>
  </section>

  <script src="{{ url_for('static', filename='js/stimgenAPI/stimgen-coblo-painter.js') }}"></script>
  <script>
    const {
      setupCanvasContext,
      drawFixationCross,
      convertMarginToAngle,
      generateRandomAngle,
      autoConfigRandomAngle,
      generateCoordinatesFromAngle,
      drawSemiBlock,
      runCoordinateDistribution,
      showMargins,
      setupCanvas,
      clearCanvas,
      sampleWithReplacement,
      pickChangeLocation,
      changeLocationManipulation,
      inverseManipulation,
      highlightChange,
      manipulateAllBlocks,
    } = painter();

    CONFIG = JSON.parse(`{{ project_settings|safe }}`);
    CONFIG.imageCenter = {
      x: CONFIG.imageWidth / 2,
      y: CONFIG.imageHeight / 2,
    };

    const navigateNewConfig = () => {
      const runMode = document.getElementById("runMode").value;
      const targetMode = document.getElementById("targetMode").value;
      const gap = document.getElementById("gap").value;
      window.location.href = `/coblo/run/{{ref_id}}/${runMode}/${targetMode}/${gap}`;
    };

    const c1 = setupCanvasContext("original");
    const c2 = setupCanvasContext("modified");

    setupCanvas([c1, c2]);

    let drawingInstructions = {};

    const drawBlocks = (coordinatesJSON) => {
      let blocks = [];
      if (!coordinatesJSON) {
        for (const sector of [1, 2, 3, 4]) {
          const colorOptions = [...CONFIG.colors];
          const angle = autoConfigRandomAngle(sector, 0, Math.PI / 2);
          const coordinates = generateCoordinatesFromAngle(angle, sector);
          blocks.push({
            coordinates,
            colors: [
              sampleWithReplacement(colorOptions),
              sampleWithReplacement(colorOptions),
            ],
            topLeftToBottomRight: Math.random() < 0.5 ? true : false,
          });
        }

        const ABlocks = JSON.parse(JSON.stringify(blocks));
        const BBlocks = JSON.parse(JSON.stringify(blocks));

        const targetLocation = pickChangeLocation(BBlocks);
        const targetMode = document.getElementById("targetMode").value;
        const runMode = document.getElementById("runMode").value;
        const showLines = document.getElementById("showLines");
        const whiteGap = document.getElementById("whiteGap");
        const showNumbers = document.getElementById("showNumbers");
        const drawDiagonalLine = document.getElementById("drawDiagonalLine");
        const shouldChangePosition = document.getElementById(
          "changePositionCheck"
        ).value;
        const changeType = document.getElementById(
          "changePositionTypeSelect"
        ).value;
        const changePositionMaxValue =
          document.getElementById("changePositionMax").value;
        const changePositionMinValue =
          document.getElementById("changePositionMin").value;
        const changePositionValue = getRandomInt(
          changePositionMinValue,
          changePositionMaxValue
        );

        const changeDirection = document.getElementById(
          "changeDirectionValueSelect"
        ).value;

        if (targetMode === "target") {
          changeLocationManipulation(targetLocation, runMode, {
            shouldChangePosition,
            changeType, // overlap, touch, or separate
            changeValue: changePositionValue, // applies to X and Y
            changeDirection, // topLeft, topRight, bottomLeft, or bottomRight
          });
        } else if (targetMode === "inverse") {
          inverseManipulation(targetLocation, runMode, BBlocks);
        } else if (targetMode === "all") {
          manipulateAllBlocks(BBlocks, runMode);
        }

        const changedBlock = targetLocation;

        drawingInstructions.ABlocks = ABlocks;
        drawingInstructions.BBlocks = BBlocks;
        drawingInstructions.targetLocation = targetLocation;

        document.getElementById("stimulus_JSON").value =
          JSON.stringify(drawingInstructions);

        document.getElementById("displayDisplacementValue").innerHTML =
          changePositionValue;
        document.getElementById("displayDisplacementDirection").innerHTML =
          changeDirection;
        document.getElementById("displayTargetManipulationType").innerHTML =
          changeType;
      } else {
        drawingInstructions = JSON.parse(coordinatesJSON);
      }

      let blockIndex = 1;
      for (const block of drawingInstructions.ABlocks) {
        drawSemiBlock(c1, block.coordinates, block.colors[0], block.colors[1], {
          gap: +document.getElementById("gap").value,
          showLines: showLines.checked,
          whiteGap: whiteGap.checked,
          blockNumber: blockIndex,
          showNumbers: showNumbers.checked,
          drawDiagonalLine: drawDiagonalLine.checked,
          drawTopLeftToBottomRight: block.topLeftToBottomRight,
        });
        blockIndex++;
      }

      blockIndex = 1;
      for (const block of drawingInstructions.BBlocks) {
        drawSemiBlock(c2, block.coordinates, block.colors[0], block.colors[1], {
          gap: +document.getElementById("gap").value,
          showLines: showLines.checked,
          whiteGap: whiteGap.checked,
          blockNumber: blockIndex,
          showNumbers: showNumbers.checked,
          drawDiagonalLine: drawDiagonalLine.checked,
          drawTopLeftToBottomRight: block.topLeftToBottomRight,
        });
        blockIndex++;
      }
    };

    function regenerate(basedOnConfig) {
      let base = null;
      if (basedOnConfig) {
        base = document.getElementById("stimulus_JSON").value;
      } else {
        drawingInstructions.targetLocation = null;
      }
      clearCanvas([c1, c2]);
      drawBlocks(base);
    }

    function toggleHighlight() {
      if (!drawingInstructions.targetLocation) {
        return alert('No blocks to change, click on "Generate" first!');
      }
      if (!drawingInstructions.targetLocation.highlighted) {
        highlightChange(drawingInstructions.targetLocation, c2);
        drawingInstructions.targetLocation.highlighted = true;
      } else {
        regenerate(true);
        drawingInstructions.targetLocation.highlighted = false;
      }
    }
  </script>
</main>
{% endblock %}

application/coblo/templates/coblo/projects.html
{% extends 'unilay.html' %}

{% block page_title %}Homepage{% endblock %}

{% block page_content %}
<main class="confined">
  <h1>Create a project</h1>
</main>
{% endblock %}